name: demo worflow
 
on:
  push:
  # workflow_dispatch:  #to manually run the workflow
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.12, 3.9, 3.8]

    env:
      NUM: 5
    
    steps:

      - name: Factorial of a number
        run: echo ${{env.NUM}}

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content
 
      - name: setup python
        uses: actions/setup-python@v4
        with:
          # python-version: "3.12" # install the python version needed
          python-version: ${{matrix.python-version}}
 
      - name: execute py script # run index.py
        run: python index.py

      - name: Run a one-line script
        run: echo Hello, World!


      - name: Run a multi-line script
        run: |
              echo "Add other actions to build"
              echo "test, and deploy your project"